theme: jekyll-theme-minimal
title: Nova Saint
description: Entrepreneur. Technology enthusiast. Product lover. Making a difference in places technology is less accessible. Helping entrepreneurs build dream products.
logo: /assets/img/nova.jpeg
